### ISSUE TITLE
Demo (still) broken

### ISSUE THREAD

**Issue by jeremyeder** [2015-Middleware-Keynote/hexboard#40]
I loved this demo when I saw it live.  Realize this repo is without a maintainer but figured I'd try it on the latest OCP 3.5.

```
root@ip-172-31-3-125: ~ # oc env dc/hexboard HEXBOARD_SIZE=2                                                                                                                                  
deploymentconfig "hexboard" updated
root@ip-172-31-3-125: ~ # oc get pods -w
NAME                READY     STATUS        RESTARTS   AGE
hexboard-1-01m38    1/1       Terminating   0          10m
hexboard-1-build    0/1       Completed     0          12m
hexboard-2-deploy   1/1       Running       0          17s
sketchpod-1-build   0/1       Completed     0          12m
sketchpod-1-k57r1   1/1       Running       0          10m
NAME               READY     STATUS        RESTARTS   AGE
hexboard-1-01m38   0/1       Terminating   0          10m
hexboard-1-01m38   0/1       Terminating   0         10m
hexboard-1-01m38   0/1       Terminating   0         10m
hexboard-2-1dsdq   0/1       Pending   0         0s
hexboard-2-1dsdq   0/1       Pending   0         0s
hexboard-2-1dsdq   0/1       ContainerCreating   0         0s
hexboard-2-1dsdq   1/1       Running   0         22s
hexboard-2-deploy   0/1       Completed   0         57s
hexboard-2-deploy   0/1       Terminating   0         57s
hexboard-2-deploy   0/1       Terminating   0         57s
hexboard-2-1dsdq   0/1       Error     0         23s
hexboard-2-1dsdq   1/1       Running   1         25s
hexboard-2-1dsdq   0/1       Error     1         26s
hexboard-2-1dsdq   0/1       CrashLoopBackOff   1         28s


root@ip-172-31-3-125: ~ # oc logs hexboard-2-1dsdq
Environment: 
        DEV_MODE=false
        NODE_ENV=production
        DEBUG_PORT=5858
Launching via npm...
npm info it worked if it ends with ok
npm info using npm@2.15.1
npm info using node@v4.6.2
npm info prestart hexboard@0.0.1
npm info start hexboard@0.0.1

> hexboard@0.0.1 start /opt/app-root/src
> node server/server.js

/opt/app-root/src/server/hexboard/hexboard.js:46
  layout.count = layout.cols * layout.rows;
                       ^

TypeError: Cannot read property 'cols' of undefined
    at new HexBoard (/opt/app-root/src/server/hexboard/hexboard.js:46:24)
    at Object.<anonymous> (/opt/app-root/src/server/hexboard/hexboard.js:128:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/app-root/src/server/api/sketch_controller.js:9:16)
    at Module._compile (module.js:409:26)

npm info hexboard@0.0.1 Failed to exec start script
npm ERR! Linux 3.10.0-514.6.1.el7.x86_64
npm ERR! argv "/opt/rh/rh-nodejs4/root/usr/bin/node" "/opt/rh/rh-nodejs4/root/usr/bin/npm" "run" "-d" "start"
npm ERR! node v4.6.2
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! hexboard@0.0.1 start: `node server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hexboard@0.0.1 start script 'node server/server.js'.
npm ERR! This is most likely a problem with the hexboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs hexboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls hexboard
npm ERR! There is likely additional logging output above.
```

**Comment by lholmquist** [comment]
@jeremyeder could you try one of these values for the HEXBOARD_SIZE  https://github.com/2015-Middleware-Keynote/hexboard/blob/master/server/config.js#L14

**Comment by jeremyeder** [comment]
Ahh, @lholmquist that worked for me.  It seems to be working correctly for me now on OCP 3.5.0.12.
